apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: airflow
  labels: 
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      initContainers:
        - name: init-airflow
          image: apache/airflow:latest
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          envFrom:
            - secretRef:
                name: postgres-credentials
          command: 
            - "/bin/bash"
            - "-c"
            - "airflow db migrate && airflow users create --username admin --password Admin --role Admin --firstname admin --lastname admin --email"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      containers:
        - name: airflow
          image: apache/airflow:latest
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          envFrom:
            - secretRef:
                name: postgres-credentials
          # volumeMounts:
          #   - name: airflow-config
          #     mountPath: /etc/airflow
          ports:
            - containerPort: 8080
          command: 
            - "/bin/bash"
            - "-c"
            - "airflow webserver"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
      # volumes:
      #   - name: airflow-config
      #     configMap:
      #       name: airflow-configmap
