apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: airflow
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
